version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "helo007-helloworld-lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-pmwwgbzgw6qt"
s3_prefix = "helo007-helloworld-lambda"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
